name: Auto Format Terraform

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths: 
      - '**.tf'
      - '**.tfvars'

jobs:
  format:
    name: Auto Format Terraform Files
    runs-on: ubuntu-latest
    
    # Only run if there are terraform file changes and not from a bot
    if: github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.5

    - name: Format Terraform Files
      run: |
        echo "Formatting Terraform files..."
        terraform fmt -recursive
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Files were formatted"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No formatting changes needed"
        fi

    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Auto-format Terraform files [skip ci]"
        git push
